### ISSUE TITLE
GitTalk

### ISSUE THREAD

**Issue by zjn-zjn** [zjn-zjn/ice#1]
http://waitmoon.com/docs/#/started 

 Description

**Comment by aha210** [comment]
**666**

**Comment by zjn-zjn** [comment]
test

**Comment by zjn-zjn** [comment]
1

**Comment by kowalski-zhang** [comment]
nice idea~

**Comment by ycj007** [comment]
请问有使用文档吗

**Comment by zjn-zjn** [comment]
> 
开发&配置demo视频：https://www.bilibili.com/video/BV1Q34y1R7KF
使用文档：http://waitmoon.com/docs/#/started

**Comment by zjn-zjn** [comment]
> 请问有使用文档吗
开发&配置demo视频：https://www.bilibili.com/video/BV1Q34y1R7KF
接入使用文档：http://waitmoon.com/docs/#/started

**Comment by zjn-zjn** [comment]
> @ycj007
> 请问有使用文档吗

开发&配置demo视频：https://www.bilibili.com/video/BV1Q34y1R7KF
接入使用文档：http://waitmoon.com/docs/#/started

**Comment by hehuilei** [comment]
client和server是什么关系？整体架构是什么样的呢

**Comment by zjn-zjn** [comment]
> client和server是什么关系？整体架构是什么样的呢

client集成在业务中，server主要用于规则的管理&配置&热更新服务。
client在启动时需要找到server拉取配置，server在规则变更时会热推送给client，server宕机时，不影响正在运行的client，只会导致新client不能启动，规则无法配置&推送

**Comment by Yidouj** [comment]
> @zjn-zjn
> > client和server是什么关系？整体架构是什么样的呢
> 
> client集成在业务中，server主要用于规则的管理&配置&热更新服务。
> client在启动时需要找到server拉取配置，server在规则变更时会热推送给client，server宕机时，不影响正在运行的client，只会导致新client不能启动，规则无法配置&推送


> @zjn-zjn
> > client和server是什么关系？整体架构是什么样的呢
> 
> client集成在业务中，server主要用于规则的管理&配置&热更新服务。
> client在启动时需要找到server拉取配置，server在规则变更时会热推送给client，server宕机时，不影响正在运行的client，只会导致新client不能启动，规则无法配置&推送

**Comment by Yidouj** [comment]
您好，请问server服务是不能集群部署吗？ client启动时找到server拉取配置，是会保存到client服务本地文件吗？

**Comment by HrbWyz** [comment]
可以支持一个登录页面吗

**Comment by zjn-zjn** [comment]
> @Yidouj
> 您好，请问server服务是不能集群部署吗？ client启动时找到server拉取配置，是会保存到client服务本地文件吗？

server目前不支持集群部署，server宕机后不影响正在运行的client

**Comment by zjn-zjn** [comment]
> @HrbWyz
> 可以支持一个登录页面吗

在规划实现中~

**Comment by fringzhao** [comment]
当流程某个节点发生错误的时候，节点落盘，待恢复后继续流程，这部分功能在哪里有介绍？这对一个长业务链太重要了

**Comment by liuhuapiaoyuan** [comment]
能自定义节点吗？前后端能分离吗

**Comment by wallyhung** [comment]
awesome

**Comment by zjn-zjn** [comment]
> 能自定义节点吗？前后端能分离吗

现在就是业务方要自己定义节点的~ 前后端分离的话也可以，前端代码也开源了，这是可能没有必要，因为配置后台目前只支持单机部署，本身编辑和更新就是一个低频操作

**Comment by zjn-zjn** [comment]
> 当流程某个节点发生错误的时候，节点落盘，待恢复后继续流程，这部分功能在哪里有介绍？这对一个长业务链太重要了

在最新的0.0.9版本中，有对应的errorHandle，可以自定义异常出现时的处理方法，比如落盘(这部分业务需要自己实现)，等到异常恢复后，再重新打入ice(也是业务自己实现)

**Comment by gonker** [comment]
大佬，可以开源前端的react源码吗，因为需要做些定制化才能在公司项目推广

**Comment by zjxpcyc** [comment]
请问下，如果商业使用，有什么需要注意的，或者收费方式是什么，我们目前在选型

**Comment by ethanwanggg** [comment]
你好，建议在 ice-client-spring-boot-starter init 中， 增加重试机制。通常情况下，client 端承载着微服务其他业务能力，若 server 端宕机所导致的 微服务无法启动， 几乎是不能接受的。

public class IceNioClientInit implements CommandLineRunner {

    @Resource
    private IceClientProperties properties;

    private IceNioClient iceNioClient;

    @Override
    public void run(String... args) {
        try {
            log.info("ice client connect to server");
            connect();
        } catch (Exception e) {
            e.printStackTrace();
            log.error("ice client connect to server error", e);
            if (properties.getRetry().isEnable()) {
                new Thread(() -> {
                    boolean needRetry = true;
                    int retryTime = 0;
                    while (needRetry) {
                        try {
                            retryTime++;
                            log.error("ice client retry connect to server time [{}]", retryTime);
                            connect();
                            needRetry = false;
                        } catch (Exception ex) {
                            ex.printStackTrace();
                            log.error("ice client retry connect to server error", ex);
                            try {
                                Thread.sleep(properties.getRetry().getInterval());
                            } catch (InterruptedException exc) {
                                exc.printStackTrace();
                            }
                        }
                        // 达到重试次数，放弃
                        if (retryTime == properties.getRetry().getRetryTime()) {
                            needRetry = false;
                            log.warn("ice client retry connect to server has error with max retry time [{}]", retryTime);
                        }
                    }
                }).start();
            }
        }
        Runtime.getRuntime().addShutdownHook(new Thread(iceNioClient::destroy));
    }

    private void connect() throws Exception {
        iceNioClient = new IceNioClient(properties.getApp(), properties.getServer(), properties.getPool().getParallelism(), properties.getMaxFrameLength(), properties.getScan());
        iceNioClient.connect();
    }
}

**Comment by zjn-zjn** [comment]
> 

首先server 宕机是一个小概率事件，另外在这里做重试，大概率是重试不成功的，所以未来的重点会放在server的HA上，预计不久的版本就会推出server的HA

**Comment by zjn-zjn** [comment]
> 请问下，如果商业使用，有什么需要注意的，或者收费方式是什么，我们目前在选型

目前ice是完全开源的，遵从apache2.0开源协议。

**Comment by zjn-zjn** [comment]
> 你好，建议在 ice-client-spring-boot-starter init 中， 增加重试机制。通常情况下，client 端承载着微服务其他业务能力，若 server 端宕机所导致的 微服务无法启动， 几乎是不能接受的。
> 
> public class IceNioClientInit implements CommandLineRunner {
> 
> ```
> @Resource
> private IceClientProperties properties;
> 
> private IceNioClient iceNioClient;
> 
> @Override
> public void run(String... args) {
>     try {
>         log.info("ice client connect to server");
>         connect();
>     } catch (Exception e) {
>         e.printStackTrace();
>         log.error("ice client connect to server error", e);
>         if (properties.getRetry().isEnable()) {
>             new Thread(() -> {
>                 boolean needRetry = true;
>                 int retryTime = 0;
>                 while (needRetry) {
>                     try {
>                         retryTime++;
>                         log.error("ice client retry connect to server time [{}]", retryTime);
>                         connect();
>                         needRetry = false;
>                     } catch (Exception ex) {
>                         ex.printStackTrace();
>                         log.error("ice client retry connect to server error", ex);
>                         try {
>                             Thread.sleep(properties.getRetry().getInterval());
>                         } catch (InterruptedException exc) {
>                             exc.printStackTrace();
>                         }
>                     }
>                     // 达到重试次数，放弃
>                     if (retryTime == properties.getRetry().getRetryTime()) {
>                         needRetry = false;
>                         log.warn("ice client retry connect to server has error with max retry time [{}]", retryTime);
>                     }
>                 }
>             }).start();
>         }
>     }
>     Runtime.getRuntime().addShutdownHook(new Thread(iceNioClient::destroy));
> }
> 
> private void connect() throws Exception {
>     iceNioClient = new IceNioClient(properties.getApp(), properties.getServer(), properties.getPool().getParallelism(), properties.getMaxFrameLength(), properties.getScan());
>     iceNioClient.connect();
> }
> ```
> 
> }

首先server 宕机是一个小概率事件，另外在这里做重试，大概率是重试不成功的，所以未来的重点会放在server的HA上，预计不久的版本就会推出server的HA

**Comment by zjn-zjn** [comment]
> 你好，建议在 ice-client-spring-boot-starter init 中， 增加重试机制。通常情况下，client 端承载着微服务其他业务能力，若 server 端宕机所导致的 微服务无法启动， 几乎是不能接受的。
> 
> public class IceNioClientInit implements CommandLineRunner {
> 
> ```
> @Resource
> private IceClientProperties properties;
> 
> private IceNioClient iceNioClient;
> 
> @Override
> public void run(String... args) {
>     try {
>         log.info("ice client connect to server");
>         connect();
>     } catch (Exception e) {
>         e.printStackTrace();
>         log.error("ice client connect to server error", e);
>         if (properties.getRetry().isEnable()) {
>             new Thread(() -> {
>                 boolean needRetry = true;
>                 int retryTime = 0;
>                 while (needRetry) {
>                     try {
>                         retryTime++;
>                         log.error("ice client retry connect to server time [{}]", retryTime);
>                         connect();
>                         needRetry = false;
>                     } catch (Exception ex) {
>                         ex.printStackTrace();
>                         log.error("ice client retry connect to server error", ex);
>                         try {
>                             Thread.sleep(properties.getRetry().getInterval());
>                         } catch (InterruptedException exc) {
>                             exc.printStackTrace();
>                         }
>                     }
>                     // 达到重试次数，放弃
>                     if (retryTime == properties.getRetry().getRetryTime()) {
>                         needRetry = false;
>                         log.warn("ice client retry connect to server has error with max retry time [{}]", retryTime);
>                     }
>                 }
>             }).start();
>         }
>     }
>     Runtime.getRuntime().addShutdownHook(new Thread(iceNioClient::destroy));
> }
> 
> private void connect() throws Exception {
>     iceNioClient = new IceNioClient(properties.getApp(), properties.getServer(), properties.getPool().getParallelism(), properties.getMaxFrameLength(), properties.getScan());
>     iceNioClient.connect();
> }
> ```
> 
> }

新的开发中的版本1.1.0 已经增加server HA 和client retry机制，预计本周发布~
