### ISSUE TITLE
使用spring-boot-devtools导致注入bean问题

### ISSUE THREAD

**Issue by jimmyqin** [zjn-zjn/ice#17]
描述: 当devtools开启后, 会导致节点中注入的bean属性无法注入问题

**Comment by zjn-zjn** [comment]
这个原因是因为 devtools使用的是 RestartClassLoader，而ice在class.forName获取类型时，采用的是系统默认的，因为类加载器不一致而导致无法通过beanType获取到正确的bean，将在1.3.0中兼容
