### ISSUE TITLE
0.0.8版本的springboot-starter配置有误

### ISSUE THREAD

**Issue by wssy001** [zjn-zjn/ice#3]
你的ice-client-spring-boot-starter:0.0.8打包的方式有误，无法正常下载到相对应的模块。
考虑将
```xml
<version>${project.version}</version>
```
换成
```xml
<version>0.0.8</version>
```
或者如下设置：
```xml
<properties>
    <ice-server.version>0.0.8</ice-server.version>
</properties>

<dependencies>
    <dependency>
        <groupId>com.waitmoon.ice</groupId>
        <artifactId>ice-client-spring-boot-autoconfigure</artifactId>
        <version>${ice-server.version}</version>
    </dependency>
</dependencies>
```

**Comment by wssy001** [comment]
![image](https://user-images.githubusercontent.com/22979223/157698311-7b5e026b-bc49-482f-8263-3d3e44d503aa.png)
如图所示，若此时回车Web提示”no available client app:2“  （client为写任何代码，application.yml中ice.app值已设置为2）
![image](https://user-images.githubusercontent.com/22979223/157698465-85183cbb-7824-4805-92b3-a3c6dba7b9b4.png)
该怎么解决呢？

**Comment by zjn-zjn** [comment]
1.关于project.version，我在本机maven3.6.3没有办法复现这个问题，是可以拉取到jar包的，不过后续还是会考虑不再使用project.version
2.ice.sh的stop脚本，会优先使用kill -15 在两秒一次检查并检查10s后，若还没有kill，则直接kill -9，这与0.0.7版本逻辑是一致的
3.no available client 表示当前没有可用的client，检查下client是否启动呢？因为server在创建业务相关的节点的时候，会去client校验配置的类是否存在/或是否还存在，因此需要至少一个client可用。这也是为了防止用户创建无效的业务节点

**Comment by wssy001** [comment]
问题大概是解决了，原因八成出在阿里云的maven镜像中。没正常导包导致无法获取ice-client，也导致了无法与客户端进行通信

**Comment by zjn-zjn** [comment]
> 问题大概是解决了，原因八成出在阿里云的maven镜像中。没正常导包导致无法获取ice-client，也导致了无法与客户端进行通信

冲冲冲~
