### ISSUE TITLE
建议更换序列化/反序列化框架 FastJSON

### ISSUE THREAD

**Issue by Ash-1024** [zjn-zjn/ice#8]
理由：
1、autoType漏洞频发
2、兼容性差
3、代码质量欠佳
4、维护频率不足，官方Issues已积累1.7K

**Comment by aboutZZ** [comment]
+1。为什么不用Jackson，而且是Spring默认的序列化工具

**Comment by zjn-zjn** [comment]
目前开发中的1.0.2已替换成jackson，fastjson的坑我也是踩了很多很多很多...
